#file: noinspection SpellCheckingInspection

name: CI-Android APK

env:
  main_project_module: app
  playstore_name: Beans

on:
  push:
    branches: [ main ]
    tags:
      - '**'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0 
    
      - name: set up secrets
        run: |
          echo "${{ secrets.RELEASE_KEYSTORE }}" > keystore.asc
          echo "${{ secrets.RELEASE_KEY}}" > key.asc
          gpg -d --passphrase "${{ secrets.RELEASE_KEYSTORE_PASSWORD }}" --batch keystore.asc > app/keystore.properties
          gpg -d --passphrase "${{ secrets.RELEASE_KEYSTORE_PASSWORD }}" --batch key.asc > app/key.jks          

      - name: Generate Dynamic Release Notes
        run: |
          mkdir -p tmp/whatsnew
          echo "Various improvements for you to experience..." > tmp/whatsnew/whatsnew-en-US

      - name: create and checkout branch
        if: github.event_name == 'pull_request'
        env:
          BRANCH: ${{ github.head_ref }}
        run: git checkout -B "$BRANCH"

      - name: set up JDK
        uses: actions/setup-java@v6
        with:
          java-version: 21
          distribution: "temurin"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Run unit tests
        run: ./gradlew testDebugUnitTest

      - name: Build APK
        run: |
          VERSION_CODE=$(git rev-list --count HEAD)
          VERSION_BASE=$(git describe --tags --abbrev=0 | sed 's/^v//')
          VERSION_DEV=$(git rev-list --count $(git describe --tags --abbrev=0)..HEAD)
          if [ $VERSION_DEV -gt 0 ]; then
            VERSION_NAME="${VERSION_BASE}.${VERSION_DEV}"
          else
            VERSION_NAME="${VERSION_BASE}"
          fi
          ./gradlew bundleSignedRelease assembleSignedRelease -PVERSION_CODE=$VERSION_CODE -PVERSION_NAME=$VERSION_NAME
        # ./gradlew assembleSignedRelease -PVERSION_CODE=$VERSION_CODE -PVERSION_NAME=$VERSION_NAME
        # ./gradlew bundleSignedRelease -PVERSION_CODE=$VERSION_CODE -PVERSION_NAME=$VERSION_NAME

      - name: Upload APK
        uses: actions/upload-artifact@v7
        with:
          path: app/build/outputs/apk/signedRelease/app-signedRelease.apk
          compression-level: 0
          archive: false

      - name: Release
        uses: softprops/action-gh-release@v3
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            app/build/outputs/apk/signedRelease/app-signedRelease.apk
          prerelease: |
            if [[ ${{ github.ref }} =~ ^refs/tags/[0-9]+\.[0-9]+[a-z]+$ ]]; then
              echo "false"
            else
              echo "true"
            fi

      - name: Upload to Google Play
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: net.helcel.beans
          releaseFiles: app/build/outputs/bundle/signedRelease/app-signedRelease.aab
          tracks: ${{ startsWith(github.ref, 'refs/tags/') && 'production' || 'alpha' }}
          status: completed
          whatsNewDirectory: tmp/whatsnew
